### ISSUE TITLE
Wikiホーム更新

### ISSUE THREAD

**Issue by sftwtms** [ryotako/igor-CommandPanel#2]
#1 に関連した更新がされていません。
「このプロシージャはIgor Pro 7では正常に動作しません！」以降の削除をお願いいたします。

**Comment by ryotako** [comment]
修正しました！
プルリクともどもありがとうございます！

実は私、就職に伴いIgorProを使わない環境に移ってしまいました。GitHubからのメールはチェックするつもりですが、対応が遅くなるかもしれません。

もし、このリポジトリのコラボレータなることに興味がおありなら、ご連絡ください。
（あるいは、このリポジトリのクローンから独自開発していって頂いても全く問題ないです）
